name: pr-lint-title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  pull-requests: read

jobs:
  pr-lint-title:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
      - name: Install commitlint
        run: |
          npm install @commitlint/config-conventional@19.5.0
          npm install commitlint@19.2.0
      - name: Generate config file
        # Here we define our custom rules for commitlint
        # Reference of all rules: https://commitlint.js.org/reference/rules.html
        run: |
          tee -a .commitlintrc.yml << END
          extends: ["@commitlint/config-conventional"]
          rules:
            "subject-case": [2, "always", ["sentence-case"]]
          END
      - name: Lint PR title
        # Use an environment variable to avoid a security vulnerability
        # https://stackoverflow.com/a/76679447
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo $PR_TITLE | npx commitlint --verbose
